### ISSUE TITLE
Can Combine take XSLT that imports other XSLT?

### ISSUE THREAD

**Issue by cmharlow** [tulibraries/aggregator_mdx#1]
See an example of where included XSLT templates here: https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/blob/master/XSLT/memphisp13039coll1dctomods.xsl#L8

Including templates in this manner can help reuse common transforms like shared schema mappings, normalizations or lookups. 

Can Combine handle this?

**Comment by cmharlow** [comment]
Yes, but requires special set up. @bibliotechy okay to close this ticket + reopen the required setup tickets on the appropriate playbook or infra repo? with ticket here to doc what metadata folks need to do to use multiple xmls?

**Comment by cmharlow** [comment]
ping @bibliotechy

**Comment by bibliotechy** [comment]
The answer is yes, they can. From the Combine slack

> There is a bit of discussion for including _local_ includes here: https://combine.readthedocs.io/en/master/configuration.html#local-includes
In essence, all sheets that are included must be transformation scenarios of their own.  When they are created and saved, they are saved locally on the filesystem with a unique filepath; this is what is added for the `<xsl:import>` in the “main” XSL file.  Those transformations that are used for include only, you can check the “Use as include” checkbox that will hide it from menus for selecting transformations, as it’s really only useful as an include.

In the explained approach, they would all need to be uploaded via the Combine UI, and the master xslt would need to reference their path in the file system. There is no need for new tickets on any playbook or infra repos.

However, I'm going to open an exploratory ticket on this repo to consider if there is another way to get xslt on to the combine machine outside UI and then reference them together?
