### ISSUE TITLE
Use pre-uploaded xslt for includes?

### ISSUE THREAD

**Issue by bibliotechy** [tulibraries/aggregator_mdx#2]
In #1 we determined that Combine XSLT can include other xslt, but the current method requires hardcoding path to other files uploaded via the Combine UI.

Wondering if it is possible to get the XSLT onto the combine machine outside the bands of the UI (some deploy process) and reference it?  LIke a known path where github repo can be pulled down, and then references can be relative rather than absolute?

This would allow the XSLT to work both in and outside of combine, so we could add automated testing, in the repo, but still have it work.

**Comment by cmharlow** [comment]
I thought one of the goals of this repo was a place to do exactly that - a git repo where metadata folks load xslt, test, share, open issues on, etc. ; then this is cloned into the working environment?
